<a href="https://colab.research.google.com/github/WhiteWolf088/Python_Tutorials/blob/main/Session_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **FUNCTIONS** 

In [28]:
def func1():  #format to define a function 
  print("Hello!") 
  
func1()   #calling a function 

Hello!


In [29]:
def func1():  #format to define a function 
  print("Hello!") 
  print("How do you do?")
func1()   #calling a function once 
func1()
func1()

Hello!
How do you do?
Hello!
How do you do?
Hello!
How do you do?


In [30]:
def ask_name():
  name = input("Enter your name :")
  print("Your name is ",name)

ask_name()

Enter your name :Pavan Kumar Reddy
Your name is  Pavan Kumar Reddy


In [31]:
def my_function(name):
  print("Hello!",name)
  print("How do you do?")
  print()

my_function("user1")   
my_function("user2")
my_function("user3")
my_function("user4")

Hello! user1
How do you do?

Hello! user2
How do you do?

Hello! user3
How do you do?

Hello! user4
How do you do?



In [32]:
def add(n1,n2):
  result = n1 + n2
  print("Result :",result)

add(5,5)

Result : 10


In [33]:
def add(n1,n2):
  result = n1 + n2
  return result #return terminates the function immediately and the control goes back to the place from where the function call was made 

result = add(5,2)
print(result)

7


In [34]:
def Arithmetic_Operations(x,y):
  c = x + y 
  d = x - y
  e = x / y
  f = x * y
  return c,d,e,f  

sum,diff,div,mul = Arithmetic_Operations(5,4)
print("SUM of the numbers:",sum)
print("Difference of the numbers:",diff)
print("Division of the numbers:",div)
print("Product of the numbers:",mul)

SUM of the numbers: 9
Difference of the numbers: 1
Division of the numbers: 1.25
Product of the numbers: 20


In [35]:
def my_function(name):
  print("Hello!",name)
  return 
  print("How do you do?")
  
my_function("user 1")

Hello! user 1


In [36]:
def my_function(name1,name2):
  print(name1,name2)
my_function("user1", "user2")

user1 user2


In [37]:
def ask_yes_no(prompt):
  while True:  #forever loop
    answer = input(prompt + '(y or n) ')
    if answer == 'y' or answer == 'Y':
      return True       #return here terminates the function
    if answer == 'n' or answer == 'N':
      return False
    print("Asnwer 'y' or 'n' ")



if ask_yes_no("Do you like ice cream?"):
  print("You like ice cream") 
else:
  print("you don't like ice cream")  

Do you like ice cream?(y or n) n
you don't like ice cream


# **NUMPY**

In [38]:
#importing the numpy library 

In [39]:
import numpy as np 

In [40]:
a = np.array([1.1,2,3,4,5])
a

array([1.1, 2. , 3. , 4. , 5. ])

In [41]:
print(a)

[1.1 2.  3.  4.  5. ]


In [42]:
type(a)   #type of a 

numpy.ndarray

In [43]:
a.dtype  #type of elements inside a 

dtype('float64')

In [44]:
a.ndim

1

In [45]:
a.size

5

In [46]:
b = np.array([5,3,7,1,8,4])
b

array([5, 3, 7, 1, 8, 4])

In [47]:
np.sort(b)  #faster to give the output 

array([1, 3, 4, 5, 7, 8])

In [48]:
b.sort()
b

array([1, 3, 4, 5, 7, 8])

In [49]:
b.size      #size is an attribute   # sort() is a method

6

In [50]:
b.ndim

1

In [51]:
b.shape  #1row 6 coumns

(6,)